// <auto-generated />
using InnoShop.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InnoShop.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20240912213439_createProductTable")]
    partial class createProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InnoShop.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Phone",
                            Description = "Ultra modern new phone with A14383 processor, and 25w charger, not included :( !!!",
                            ImageUrl = "https://placeholder.co/600x400",
                            Name = "IPhone 37",
                            Price = 130.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Phone",
                            Description = "Brand new flagship, with touch screen, 1500 watt charging, case, iPhone charger, car and apartment included.",
                            ImageUrl = "https://placeholder.co/600x400",
                            Name = "Samsung Galaxy s47+ UltraXXL SuperMega AmoledXL",
                            Price = 110.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Phone",
                            Description = "New pricing principle. $10 phone, but a little more advertising. 780 megapixel camera, iPhone charger included.",
                            ImageUrl = "https://placeholder.co/600x400",
                            Name = "Xiaomi Redmi Note 154X Ultra Plus 9G+ ultra",
                            Price = 10.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Notebook",
                            Description = "NVIDIA 15990 128gb Cyberpunck 30fps in 2k guaranteed!!!, Intel Core 23 9999K XL, 100Tb M2, daydreaming. Default notebook.",
                            ImageUrl = "https://placeholder.co/600x400",
                            Name = "Lenovo B-best 431",
                            Price = 50.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
